=begin
#Polar Accesslink API

#Polar Accesslink API documentation

OpenAPI spec version: 3.59.0
Contact: b2bhelpdesk@polar.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.16

=end

require 'spec_helper'
require 'json'

# Unit tests for PolarAccesslink::ExercisesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ExercisesApi' do
  before do
    # run before each test
    @instance = PolarAccesslink::ExercisesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExercisesApi' do
    it 'should create an instance of ExercisesApi' do
      expect(@instance).to be_instance_of(PolarAccesslink::ExercisesApi)
    end
  end

  # unit tests for get_exercise_fit_without_transaction
  # Get exercise FIT
  # FIT file for users exercise.
  # @param exercise_id Hashed exercise id.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_exercise_fit_without_transaction test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_exercise_without_transaction
  # Get exercise
  # Get users exercise using hashed id.
  # @param exercise_id Hashed exercise id.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_exercise_without_transaction test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_exercises_without_transaction
  # List exercises
  # List users exercises available in Accesslink.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'list_exercises_without_transaction test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
