=begin
#Polar Accesslink API

#Polar Accesslink API documentation

OpenAPI spec version: 3.59.0
Contact: b2bhelpdesk@polar.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.16

=end

require 'spec_helper'
require 'json'

# Unit tests for PolarAccesslink::NightlyRechargeApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'NightlyRechargeApi' do
  before do
    # run before each test
    @instance = PolarAccesslink::NightlyRechargeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NightlyRechargeApi' do
    it 'should create an instance of NightlyRechargeApi' do
      expect(@instance).to be_instance_of(PolarAccesslink::NightlyRechargeApi)
    end
  end

  # unit tests for list_nightly_recharge
  # List Nightly Recharges
  # List Nightly Recharge data of user for the last 28 days.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'list_nightly_recharge test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v3_users_nightly_recharge_date_get
  # Get Nightly Recharge
  # Get Users Nightly Recharge data for given date.
  # @param date Date of Nightly Recharge as ISO-8601 date string, example: \&quot;2020-01-01\&quot;
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v3_users_nightly_recharge_date_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
