=begin
#Polar Accesslink API

#Polar Accesslink API documentation

The version of the OpenAPI document: 3.40.0
Contact: b2bhelpdesk@polar.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PolarAccesslink::PhysicalInfoApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PhysicalInfoApi' do
  before do
    # run before each test
    @api_instance = PolarAccesslink::PhysicalInfoApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PhysicalInfoApi' do
    it 'should create an instance of PhysicalInfoApi' do
      expect(@api_instance).to be_instance_of(PolarAccesslink::PhysicalInfoApi)
    end
  end

  # unit tests for commit_physical_info_transaction
  # Commit transaction
  # After successfully retrieving physical information within a transaction, partners are expected to commit the transaction.
  # @param transaction_id Transaction identifier
  # @param user_id User identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'commit_physical_info_transaction test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_physical_info_transaction
  # Create transaction
  # Initiate physical info transaction. Check for new physical info and create a new transaction if found.
  # @param user_id User identifier
  # @param [Hash] opts the optional parameters
  # @return [TransactionLocation]
  describe 'create_physical_info_transaction test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_physical_info
  # Get physical info
  # Get physical info entity data
  # @param user_id User identifier
  # @param transaction_id Transaction identifier
  # @param physical_info_id Physical information identifier
  # @param [Hash] opts the optional parameters
  # @return [PhysicalInformation]
  describe 'get_physical_info test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_physical_infos
  # List physical infos
  # List new physical info data. After successfully initiating a transaction, physical infos included within it can be retrieved with the provided transactionId.
  # @param transaction_id Transaction identifier
  # @param user_id User identifier
  # @param [Hash] opts the optional parameters
  # @return [PhysicalInformations]
  describe 'list_physical_infos test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
