=begin
#Polar Accesslink API

#Polar Accesslink API documentation

OpenAPI spec version: 3.59.0
Contact: b2bhelpdesk@polar.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.16

=end

require 'spec_helper'
require 'json'

# Unit tests for PolarAccesslink::PullNotificationsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PullNotificationsApi' do
  before do
    # run before each test
    @instance = PolarAccesslink::PullNotificationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PullNotificationsApi' do
    it 'should create an instance of PullNotificationsApi' do
      expect(@instance).to be_instance_of(PolarAccesslink::PullNotificationsApi)
    end
  end

  # unit tests for list
  # List
  # Get list of available exercises and activities for users
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
