=begin
#Polar Accesslink API

#Polar Accesslink API documentation

OpenAPI spec version: 3.59.0
Contact: b2bhelpdesk@polar.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.16

=end

require 'spec_helper'
require 'json'

# Unit tests for PolarAccesslink::SleepApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SleepApi' do
  before do
    # run before each test
    @instance = PolarAccesslink::SleepApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SleepApi' do
    it 'should create an instance of SleepApi' do
      expect(@instance).to be_instance_of(PolarAccesslink::SleepApi)
    end
  end

  # unit tests for list_nights
  # List nights
  # List sleep data of user for the last 28 days.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'list_nights test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v3_users_sleep_available_get
  # Get available sleep times
  # Get the dates with sleep start and end times, where user has sleep data available in the last 28 days.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v3_users_sleep_available_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v3_users_sleep_date_get
  # Get Sleep
  # Get Users sleep data for given date.
  # @param date Date of sleep as ISO-8601 date string, example: \&quot;2020-01-01\&quot;
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v3_users_sleep_date_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
