=begin
#Polar Accesslink API

#Polar Accesslink API documentation

The version of the OpenAPI document: 3.40.0
Contact: b2bhelpdesk@polar.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PolarAccesslink::AvailableUserData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AvailableUserData' do
  before do
    # run before each test
    @instance = PolarAccesslink::AvailableUserData.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AvailableUserData' do
    it 'should create an instance of AvailableUserData' do
      expect(@instance).to be_instance_of(PolarAccesslink::AvailableUserData)
    end
  end
  describe 'test attribute "user_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "data_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["EXERCISE", "ACTIVITY_LOG", "ACTIVITY_SUMMARY", "PHYSICAL_INFORMATION"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.data_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "url"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
