=begin
#Polar Accesslink API

#Polar Accesslink API documentation

The version of the OpenAPI document: 3.40.0
Contact: b2bhelpdesk@polar.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PolarAccesslink::WebhookPing
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WebhookPing' do
  before do
    # run before each test
    @instance = PolarAccesslink::WebhookPing.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhookPing' do
    it 'should create an instance of WebhookPing' do
      expect(@instance).to be_instance_of(PolarAccesslink::WebhookPing)
    end
  end
  describe 'test attribute "timestamp"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "event"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["PING"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.event = value }.not_to raise_error
      # end
    end
  end

end
