=begin
#Polar Accesslink API

#Polar Accesslink API documentation

The version of the OpenAPI document: 3.40.0
Contact: b2bhelpdesk@polar.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PolarAccesslink::WebhookType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WebhookType' do
  before do
    # run before each test
    @instance = PolarAccesslink::WebhookType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhookType' do
    it 'should create an instance of WebhookType' do
      expect(@instance).to be_instance_of(PolarAccesslink::WebhookType)
    end
  end
end
