=begin
#Polar Accesslink API

#Polar Accesslink API documentation

OpenAPI spec version: 3.59.0
Contact: b2bhelpdesk@polar.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.16

=end

# Common files
require 'polar_accesslink/api_client'
require 'polar_accesslink/api_error'
require 'polar_accesslink/version'
require 'polar_accesslink/configuration'

# Models

# APIs
require 'polar_accesslink/api/daily_activity_api'
require 'polar_accesslink/api/exercises_api'
require 'polar_accesslink/api/nightly_recharge_api'
require 'polar_accesslink/api/physical_info_api'
require 'polar_accesslink/api/pull_notifications_api'
require 'polar_accesslink/api/sleep_api'
require 'polar_accesslink/api/training_data_api'
require 'polar_accesslink/api/users_api'
require 'polar_accesslink/api/webhooks_api'

module PolarAccesslink
  class << self
    # Customize default settings for the SDK using block.
    #   PolarAccesslink.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
